export default [
  '{',
  '  "name": "PWA application",',
  '  "short_name": "PWApp",',
  '  "background_color": "#FFF",',
  '  "theme_color": "#FFF",',
  '  "categories": ["Web dev", "PWA", "Software"],',
  '  "shortcuts": [',
  '    {',
  '      "name": "Something cool",',
  '      "url": "/",',
  '      "icons": [', 
  '        {',
  '          "src": "/assets/icons/icon_120.png",',
  '          "sizes": "120x120",',
  '          "type": "image/png"',
  '        }',
  '      ]',
  '    }',
  '  ],',
  '  "icons": [',
  '    {',
  '      "src": "/assets/icons/icon_192.png",',
  '      "sizes": "192x192",',
  '      "type": "image/png"',
  '    }',
  '  ],',
  '  "screenshots": [',
  '    {',
  '      "src": "/assets/screenshots/screen1.png"',
  '    },',
  '    {',
  '      "src": "/assets/screenshots/screen2.png"',
  '    },',
  '    {',
  '      "src": "/assets/screenshots/screen3.png"',
  '    },',
  '    {',
  '      "src": "/assets/screenshots/screen4.png"',
  '    }',
  '  ]',
  '}'
].join('\n');